

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FormsAuthenticationMvc_Demo.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EmployeeContext : DbContext
{
    public EmployeeContext()
        : base("name=EmployeeContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<UserRolesMapping> UserRolesMappings { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

}

}

